FROM ubuntu:20.04
RUN apt-get update -y && apt-get install curl -y && apt-get install gnupg -y
RUN curl -sS http://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
RUN echo "deb http://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
RUN apt-get update
RUN apt-get install -y apt-utils nodejs yarn
RUN apt-get install npm -y
RUN yarn global add serverless
RUN apt-get install software-properties-common -y  && apt-get upgrade -y && apt install python3-pip -y && apt-get install git -y && apt-get install python3-venv -y
RUN apt-get -y install sudo -y
RUN mkdir /home/appfiles
WORKDIR home/appfiles
CMD ["sleep","infinity"]